<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wp_deqar_reports"
 *
 * Auto generated by Extension Builder 2021-09-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'DEQAR Report upload',
    'description' => '',
    'category' => 'plugin',
    'author' => 'WEBprofil',
    'author_email' => 'office@webprofil.at',
    'state' => 'alpha',
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
